#!/bin/bash

#Requires: xdotool 
#Optional to hide mouse: unclutter

##################
#Check           #
#requirements    #
##################


if [ ! -f /usr/bin/xdotool ]
then
echo "xdotool is required, please install it before running this script"
exit
fi


##################
#Ctrl+C action   #
##################
unclutteractive=0

trap ctrl_c INT

function ctrl_c() {

        if [ $unclutteractive -eq 1 ] && [ $mous == 'n' ]
        then
       
        killall unclutter
        
        fi
        
        exit
}

##################
#Ask for keys    #
##################

echo "##############################################"
echo "# Welcome to MouseToKeyCamera (Made by Azul) #"
echo "##############################################"

##################
#Set Speed       #
##################


echo "##############################################"
echo "Enter speed of camera (number of seconds to wait between keydown and keyup): " 
echo ""
read -p "Press just Enter to use Default (0.001): " delay
echo ""
if [ -z "$delay" ]
then
delay=0.001
fi
echo "##############################################"
echo "##############################################"


echo "########     Select your keys map:   #########"
echo "##############################################"


read -p "Enter key (just one letter) for RIGHT_BUTTON (RIGHT AXIS): " right_button
echo "##############################################"
read -p "Enter key (just one letter) for LEFT_BUTTON (LEFT AXIS): " left_button
echo "##############################################"
read -p "Enter key (just one letter) for UP_BUTTON (UP AXIS): " up_button
echo "##############################################"
read -p "Enter key (just one letter) for DOWN_BUTTON (DOWN AXIS): " down_button
echo "##############################################"


##################
#Check mouseclick#
##################

if [ -f ./mouseclick ]
then
read -p "Do you want to map mouse clicks? y/n: " mous
echo "##############################################"
else
echo "You dont have mouseclick here to map mouse clicks."
echo "Download it from https://github.com/rubenxi/MouseToKeyboardCamera/tree/mouseclick"
echo "Compile mouseclick.c with gcc -lX11 mouseclick.c -o mouseclick"
echo "Place the output in the same folder as MouseToKeyboardCamera to use it."
echo "##############################################"
mous=n
fi

unc=n

##################
#Check unclutter #
##################

if [ -f /usr/bin/unclutter ]

then
read -p "unclutter found, do you want to use it to make mouse invisible? y/n: " unc
echo "##############################################"
else
echo "unclutter dont found, you cant hide the mouse"
echo "##############################################"
fi

if [ $unc == 'y' ] 
then
unclutteractive=1
/usr/bin/unclutter -idle 0 -jitter 1000000000000000 &
fi

##################
#If wants to use #
#clicks          #
##################

if [ $mous == 'y' ]
then


read -p "Enter key (just one letter) for X_BUTTON (LEFT CLICK): " x_button
echo "##############################################"
read -p "Enter key (just one letter) for A_BUTTON (RIGHT CLICK): " a_button
echo "##############################################"


read -p "Do you want to configure extra buttons? y/n: " yes
echo "##############################################"

if [ $yes == 'y' ]
then
echo "##############################################"
read -p "Enter key (just one letter) for MIDDLE CLICK: " midb
echo "##############################################"

read -p "Enter key (just one letter) for UP WHEEL: " upmb
echo "##############################################"

read -p "Enter key (just one letter) for DOWN WHEEL: " downmb

echo "##############################################"
read -p "Enter key (just one letter) for SIDE UP BUTTON: " upsideb

echo "##############################################"
read -p "Enter key (just one letter) for SIDE DOWN BUTTON: " downsideb
echo "##############################################"



echo ""
echo "##############################################"
echo "Starting mouseclick..."
echo "##############################################"
echo ""
./mouseclick $x_button $a_button $midb $upmb $downmb $upsideb $downsideb $unc &

else
echo ""
echo "##############################################"
echo "Starting mouseclick..."
echo "##############################################"
echo ""

./mouseclick $x_button $a_button $unc &

fi




else

        if [ $unclutteractive -eq 1 ] && [ $mous == 'n' ]
        then
       echo "##############################################"
       echo "##############################################"
        echo "Using unclutter without mouseclick maping is not recommended as you will see the mouse disappearing and appearing while moving it. This is because of unclutter limitations and it won´t be fixed by now."
       echo "##############################################" 
       echo "##############################################"
       fi

echo "DONE, CHANGE TO GAME TAB NOW"
echo "PRESS CTRL+C IN THIS WINDOWS TO STOP SCRIPT"

fi




##################
#Get screen size #
##################

Xaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1)  >>/dev/null 2>>/dev/null
Yaxis=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)  >>/dev/null 2>>/dev/null
let "Xaxis=Xaxis/2"
let "Yaxis=Yaxis/2"

if [ $Xaxis -lt 20 ] || [ $Yaxis -lt 20 ]
then
echo "Error getting screen size, configuring default values..."
Xaxis=100
Yaxis=100
fi

##################
#Center mouse    #
##################

xdotool mousemove $Xaxis $Yaxis


var=0


##################
#Infinite Loop 1 #
#in case that use#
#unclutter but   #
#not mouseclick  #
##################
   
if [ $unc == 'y' ] && [ $mous != 'y' ]
then
   
while [ 1 -eq 1 ]; do
current=0
previous=0


             
eval $(xdotool getmouselocation --shell)

##################
#Get value of    #
#most moved axis #
##################

    right=`expr $X - $Xaxis`
    left=`expr $Xaxis - $X`
    up=`expr $Yaxis - $Y`
    down=`expr $Y - $Yaxis`
    
    a=($right $left $up $down)

    max=0
    for v in ${a[@]}; do
    if (( "$v" > "$max" )); then max=$v; fi; 
    done

    if [ $max -gt 0 ]
    then

        ##################
        #RIGHT           #
        ##################
    
    if [ $max -eq $right ]
    then
    xdotool keydown $right_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $right_button
    killall unclutter
    /usr/bin/unclutter -idle 0 -jitter 1000000000000000 &
        ##################
        #LEFT            #
        ##################
    
    elif [ $max -eq $left ]
    then
    xdotool keydown $left_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $left_button
    killall unclutter
    /usr/bin/unclutter -idle 0 -jitter 1000000000000000 &
        ##################
        #UP              #
        ##################
    
    elif [ $max -eq $up ]
    then   
    xdotool keydown $up_button
    current=$Y
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$Y
    done
    xdotool keyup $up_button
    killall unclutter
    /usr/bin/unclutter -idle 0 -jitter 1000000000000000 &
        ##################
        #DOWN            #
        ##################
     
    elif [ $max -eq $down ]
    then
    xdotool keydown $down_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $down_button
    killall unclutter
    /usr/bin/unclutter -idle 0 -jitter 1000000000000000 &
        ##################
        #END             #
        ##################
    
    fi
    
    
    xdotool mousemove $Xaxis $Yaxis
fi
    #----------------------------------------------------
         
    #------------------------------------------------
    

   
done

 # Loop 1 end

 
##################
#Infinite Loop 2 #
#in case that use#
#unclutter and   #
# mouseclick or  #
#just mouseclick #
##################

else
while [ 1 -eq 1 ]; do
current=0
previous=0


             
eval $(xdotool getmouselocation --shell)

##################
#Get value of    #
#most moved axis #
##################

    right=`expr $X - $Xaxis`
    left=`expr $Xaxis - $X`
    up=`expr $Yaxis - $Y`
    down=`expr $Y - $Yaxis`
    
    a=($right $left $up $down)

    max=0
    for v in ${a[@]}; do
    if (( "$v" > "$max" )); then max=$v; fi; 
    done

    if [ $max -gt 0 ]
    then

        ##################
        #RIGHT           #
        ##################
    
    if [ $max -eq $right ]
    then
    xdotool keydown $right_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $right_button
        ##################
        #LEFT            #
        ##################
    
    elif [ $max -eq $left ]
    then
    xdotool keydown $left_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $left_button
        ##################
        #UP              #
        ##################
    
    elif [ $max -eq $up ]
    then   
    xdotool keydown $up_button
    current=$Y
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$Y
    done
    xdotool keyup $up_button
        ##################
        #DOWN            #
        ##################
     
    elif [ $max -eq $down ]
    then
    xdotool keydown $down_button
    current=$X
    while [ $previous -ne $current ]
    do
    sleep $delay
    eval $(xdotool getmouselocation --shell)
    previous=$current
    current=$X
    done
    xdotool keyup $down_button
        ##################
        #END             #
        ##################
    
    fi
    
    
    xdotool mousemove $Xaxis $Yaxis
fi
    #----------------------------------------------------
         
    #------------------------------------------------
    

   
done

fi
